version: '3.9'

services:

  postgres-db:
    container_name: postgres2
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PDB_USER}
      - POSTGRES_PASSWORD=${PDB_PASSWORD}
      - POSTGRES_DB=${PDB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - testuzb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PDB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  migrate:
    image: migrate/migrate
    networks:
      - testuzb
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db
    command: ["-path", "/migrations", "-database" ,"postgres://${PDB_USER}:${PDB_PASSWORD}@postgres:${PDB_PORT}/${PDB_NAME}?sslmode=disable","up"]

  userservice:
    container_name: userservice
    build: .
    ports:
      - "50051:50051"
    networks:
      - testuzb
    depends_on:
      - postgres-db
      - migrate
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  testuzb:
    external: true

volumes:
  db:
    driver: local
