// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: checker.proto

package checker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CheckerService_Submit_FullMethodName = "/checker.CheckerService/Submit"
)

// CheckerServiceClient is the client API for CheckerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckerServiceClient interface {
	Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error)
}

type checkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckerServiceClient(cc grpc.ClientConnInterface) CheckerServiceClient {
	return &checkerServiceClient{cc}
}

func (c *checkerServiceClient) Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResp)
	err := c.cc.Invoke(ctx, CheckerService_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckerServiceServer is the server API for CheckerService service.
// All implementations must embed UnimplementedCheckerServiceServer
// for forward compatibility
type CheckerServiceServer interface {
	Submit(context.Context, *SubmitReq) (*SubmitResp, error)
	mustEmbedUnimplementedCheckerServiceServer()
}

// UnimplementedCheckerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckerServiceServer struct {
}

func (UnimplementedCheckerServiceServer) Submit(context.Context, *SubmitReq) (*SubmitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedCheckerServiceServer) mustEmbedUnimplementedCheckerServiceServer() {}

// UnsafeCheckerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckerServiceServer will
// result in compilation errors.
type UnsafeCheckerServiceServer interface {
	mustEmbedUnimplementedCheckerServiceServer()
}

func RegisterCheckerServiceServer(s grpc.ServiceRegistrar, srv CheckerServiceServer) {
	s.RegisterService(&CheckerService_ServiceDesc, srv)
}

func _CheckerService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckerService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServiceServer).Submit(ctx, req.(*SubmitReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckerService_ServiceDesc is the grpc.ServiceDesc for CheckerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checker.CheckerService",
	HandlerType: (*CheckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _CheckerService_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checker.proto",
}
