name: API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Check if the user-service directory exists
            if [ -d "test/user-service" ]; then
              echo "Repository exists. Pulling latest changes..."
              cd test/user-service
              git pull origin main
            else
              echo "Repository does not exist. Cloning repository..."
              git clone git@github.com:TestPlatformService/user-service.git
              cd test/user-service
            fi

            # Stop and remove existing Docker containers
            sudo docker compose down || true

            # Build and start Docker containers
            sudo docker compose up -d --build
